pipeline {
    agent any

    tools {
        maven 'maven3.3.9'
    }
    stages {
        stage('Build') {
            steps {
               dir ('docker-presentation/introduction-1/examples/spring-web') {
                  sh 'mvn clean install'
                }
            }
        }
        stage('Image Build And Push') {
            steps {
               dir ('docker-presentation/introduction-1/examples/spring-web') {
                  script {
                      def app = docker.build 'slamhan/docker-presentation/hello-world:latest'
                      app.push()
                  }
                }
            }
        }
    }
}