pipeline {
    agent any

    tools {
        maven 'maven3.3.9'
    }
    parameters {
            string(name: 'VERSION', defaultValue: 'latest', description: 'Which version to build?')
        }
    stages {
        stage('Build') {
            steps {
               dir ('docker-presentation/introduction-1/examples/spring-web') {
                  sh 'mvn clean install'
                }
            }
        }
        stage('Image Build And Push') {
            steps {
               dir ('docker-presentation/introduction-1/examples/spring-web') {
                  script {
                      def app = docker.build 'docker.finnplay.net/hello-world:${VERSION}'
                      app.push()
                  }
                }
            }
        }
    }
}